name: NineEyes
version: '0.4.3'
main: ru.velfan.NineEyes
api-version: '1.21.4'
author: SanyaFox, VelFan
description: Plugin for NineEyes
commands:
  nightvision:
    description: Дает игроку эффект ночного видения
    usage: /nightvision
    aliases: [nv, ne]



    
